export const dataProducts = () => {
  return {
    products: [
      {
        typeProduct: "Camiseta masculina",
        price: 229.99,
        genre: "masculino",
        photo: "./src/assets/products/camisetaMasc1.jpg",
        description: "camiseta preta e branca",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: true,
      },
      {
        typeProduct: "Camiseta masculina",
        price: 229.99,
        genre: "masculino",
        photo: "./src/assets/products/camisetaMasc2.jpg",
        description: "camiseta branca",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: true,
      },
      {
        typeProduct: "Camiseta masculina",
        price: 259.99,
        genre: "masculino",
        photo: "./src/assets/products/camisetaMasc3.jpg",
        description: "camiseta branca nova",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: true,
      },
      {
        typeProduct: "Camiseta masculina",
        price: 89.99,
        genre: "masculino",
        photo: "./src/assets/products/camisetaMasc4.jpg",
        description: "camiseta de homenagem",
        modelType: "Masculino",
        freteFree: false,
        bestSellers: false,
      },
      {
        typeProduct: "Camiseta masculina",
        price: 159.99,
        genre: "masculino",
        photo: "./src/assets/products/camisetaMasc5.jpg",
        description: "camiseta preta listrada",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: false,
      },
      {
        typeProduct: "Camiseta masculina",
        price: 259.99,
        genre: "masculino",
        photo: "./src/assets/products/camisetaMasc6.jpg",
        description: "camiseta preta",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: false,
      },
      {
        typeProduct: "Camiseta feminina",
        price: 79.99,
        genre: "feminino",
        photo: "./src/assets/products/camisetaFem1.jpg",
        description: "camiseta branca listrada",
        modelType: "Feminino",
        freteFree: false,
        bestSellers: true,
      },
      {
        typeProduct: "Camiseta feminina",
        price: 79.99,
        genre: "feminino",
        photo: "./src/assets/products/camisetaFem2.jpg",
        description: "camiseta preta feminina",
        modelType: "Feminino",
        freteFree: false,
        bestSellers: true,
      },
      {
        typeProduct: "Boné",
        price: 49.99,
        genre: "masculino",
        photo: "./src/assets/products/bone1.png",
        description: "boné preto",
        modelType: "Masculino",
        freteFree: false,
        bestSellers: false,
      },
      {
        typeProduct: "calça",
        price: 110.99,
        genre: "masculino",
        photo: "./src/assets/products/calça1.jpg",
        description: "calça preta e laranja",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: false,
      },
      {
        typeProduct: "calça",
        price: 110.99,
        genre: "masculino",
        photo: "./src/assets/products/calça2.jpg",
        description: "calça preta e branca",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: true,
      },
      {
        typeProduct: "calça",
        price: 110.99,
        genre: "masculino",
        photo: "./src/assets/products/calça3.jpg",
        description: "calça de moletom cinza",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: false,
      },
      {
        typeProduct: "infantil",
        price: 69.99,
        genre: "masculino",
        photo: "./src/assets/products/infantil1.jpg",
        description: "camiseta branca infantil",
        modelType: "Infantil",
        freteFree: false,
        bestSellers: false,
      },
      {
        typeProduct: "infantil",
        price: 69.99,
        genre: "feminino",
        photo: "./src/assets/products/infantil2.jpg",
        description: "conjunto infantil feminino",
        modelType: "Infantil",
        freteFree: false,
        bestSellers: true,
      },
      {
        typeProduct: "infantil",
        price: 69.99,
        genre: "masculino",
        photo: "./src/assets/products/infantil3.jpg",
        description: "conjunto infantil masculino",
        modelType: "Infantil",
        freteFree: false,
        bestSellers: true,
      },
      {
        typeProduct: "infantil",
        price: 129.99,
        genre: "masculino",
        photo: "./src/assets/products/kit-infantil.jpg",
        description: "kit infantil",
        modelType: "Infantil",
        freteFree: true,
        bestSellers: true,
      },
      {
        typeProduct: "jaqueta",
        price: 300.0,
        genre: "masculino",
        photo: "./src/assets/products/jaquetaMasc1.jpg",
        description: "jaqueta masculina",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: true,
      },
      {
        typeProduct: "jaqueta",
        price: 300.0,
        genre: "masculino",
        photo: "./src/assets/products/jaquetaMasc2.jpg",
        description: "jaqueta masculina ",
        modelType: "Masculino",
        freteFree: true,
        bestSellers: true,
      },
      {
        typeProduct: "jaqueta",
        price: 300.0,
        genre: "feminino",
        photo: "./src/assets/products/jaquetaFem1.jpg",
        description: "jaqueta feminina",
        modelType: "Feminino",
        freteFree: true,
        bestSellers: true,
      },
      {
        typeProduct: "bermuda",
        price: 70.99,
        genre: "masculino",
        photo: "./src/assets/products/bermuda1.jpg",
        description: "bermuda preta",
        modelType: "Masculino",
        freteFree: false,
        bestSellers: false,
      },
      {
        typeProduct: "bermuda",
        price: 70.99,
        genre: "masculino",
        photo: "./src/assets/products/bermuda2.png",
        description: "bermuda branca",
        modelType: "Masculino",
        freteFree: false,
        bestSellers: false,
      },
      {
        typeProduct: "Tenis",
        price: 70.99,
        genre: "feminino",
        photo: "./src/assets/products/tenis1.jpg",
        description: "tenis all star",
        modelType: "Feminino",
        freteFree: false,
        bestSellers: false,
      },
      {
        typeProduct: "Tenis",
        price: 70.99,
        genre: "masculino",
        photo: "./src/assets/products/tenis2.jpg",
        description: "max pro timão",
        modelType: "Masculino",
        freteFree: false,
        bestSellers: true,
      },
      {
        typeProduct: "pet",
        price: 20.99,
        photo: "./src/assets/products/pet-1.jpg",
        description: "lenço pet",
        modelType: "Pet",
        freteFree: false,
        bestSellers: true,
      },
      {
        typeProduct: "pet",
        price: 20.99,
        photo: "./src/assets/products/cama-pet.jpg",
        description: "cama pet",
        modelType: "Pet",
        freteFree: false,
        bestSellers: false,
      },
      {
        typeProduct: "pet",
        price: 25.99,
        photo: "./src/assets/products/coleira-pet.jpg",
        description: "coleira pet",
        modelType: "Pet",
        bestSellers: false,
      },
    ],
  };
};
